### PR TITLE
Require feature `option_shutdown_anysegwit`

### LINKED ISSUE #1006: Require option_anysegwit/Adapt API
Now that option_anysegwit has been around for a while, we should adapt the API to fetch the shutdown script to (a) allow any witness script, (b) maybe merge it with `get_destination_script`, since the two do basically the same thing.

### PR DESCRIPTION
**Pull request by jkczyz**
Fixes #1006.

TODO: Fix `full_stack` fuzz test failure likely caused by:

```
Invalid funding_created signature from peer
```

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Needs rebase on keysend.

**Comment by TheBlueMatt** [comment]
Grrrrrr, I'm more than a little bit pissed about this, but it looks like maybe lnd doesn't support shutdown_anysegwit? At least my immediate peers don't seem to support it. I've asked on their slack but its a bit disappointing that a 2-year-old spec change isn't supported. It's quite annoying, but I guess we could simply document this and then check if the peer supports anysegwit when we open the channel?

**Comment by jkczyz** [comment]
> Grrrrrr, I'm more than a little bit pissed about this, but it looks like maybe lnd doesn't support shutdown_anysegwit? At least my immediate peers don't seem to support it. I've asked on their slack but its a bit disappointing that a 2-year-old spec change isn't supported. It's quite annoying, but I guess we could simply document this and then check if the peer supports anysegwit when we open the channel?

Hmmm... looks like it was only merged into the spec back on May 24 of this year. Could check at channel open and would also need to check at close after #1019.

**Comment by jkczyz** [comment]
Though it would make our interfaces more complicated if the validity of the user's shutdown script provided by `KeysInterface` depended on the counterparty's features.

**Comment by TheBlueMatt** [comment]
> Hmmm... looks like it was only merged into the spec back on May 24 of this year

It's been around for much longer, though. At least it's super trivial to implement, too.

> Though it would make our interfaces more complicated if the validity of the user's shutdown script provided by KeysInterface depended on the counterparty's features.

I think we should just force-close in that case and document it. Hopefully eventually lnd will implement it and until then warning users is fine I think.

**Comment by TheBlueMatt** [comment]
#1019 is going ahead without requiring `anysegwit`. I don't think there's a reason to require it any time soon.

**Pull request closed without merging**
