### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by elichai**
Updating `rust-bitcoin` to latest 0.20, and `rust-secp256k1` to 0.15.
Removed `bitcoin_hashes` and reused the one that is now re-exported from `rust-bitcoin` (https://github.com/rust-bitcoin/rust-bitcoin/pull/289)

I rebased my wasm tests on top of this and updated the test and I can verify that after this the code here 100% supports wasm :)
https://github.com/elichai/rust-lightning/tree/wasm/wasm-test 

One thing that a bit bothered me and should be double checked is that we only use usize for the weight, not for the fees themselves. (otherwise it won't be enough for 32 bit systems)

cc https://github.com/rust-bitcoin/rust-bitcoin/pull/298

### CODE REVIEW

**Comment by elichai** [comment]
Maybe replacing `as u64` with `u64::from()` can be a good idea and will promise us that we won't demote any integer and lose bits

**Comment by TheBlueMatt** [comment]
Why drop the explicit bitcoin_hashes? As long as they're bumped together it shouldn't matter (and what about ensuring it gets the fuzztarget feature?).

Anyway, looks awesome!

**Comment by elichai** [comment]
hmm the point of using `bitcoin::hashes` is for future robustness, but if you prefer I can revert this part.
anyhow, rust-bitcoin propagates this feature to `bitcoin_hashes` https://github.com/rust-bitcoin/rust-bitcoin/blob/master/Cargo.toml#L18

As a middle ground, we can in the code use `bitcoin::hashes` but also in the Cargo.toml import it to make sure we propagate the feature (although then in the future it can get out of sync without anyone noticing)

**Comment by TheBlueMatt** [comment]
Using the bitcoin-exported copy only provides robustness if we want to depend on a different hashes than upstream so that downstream users don't have to upgrade to the latest hashes to upgrade, but we're not doing that here.

**Comment by elichai** [comment]
Ok, I changed it back to use `bitcoin_hashes`

**Pull request merged**
