### PR TITLE
Implement and document Channel/ChannelManager (de)serialization

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Based on #217 and #222.

I'm sure there are bugs hiding in various state transitions and interaction with serialize/deserialize, and definitely need to think harder about potential for funds loss on deserializing old states with pending HTLC closure due to conflicts between deserialized ChannelManager/ChannelMonitors, but need to get the big API changes landed here first.

### CODE REVIEW

**Comment by yuntai** [comment]
think there is a bug in one condition checking in fn send_commitment(). 

https://github.com/rust-bitcoin/rust-lightning/pull/223/files#diff-40049ab371072bb899cde6c5f42bcae6R3131

was not sure comment on the closed pr get notified.

**Comment by TheBlueMatt** [comment]
Hmm, github doesn't auto-open files so your like is actually busted. Can you comment on the line you think is wrong?

**Comment by yuntai** [comment]
https://github.com/rust-bitcoin/rust-lightning/pull/213#discussion_r228486019 

this link works?

**Comment by TheBlueMatt** [comment]
Oops, indeed, will fix in #226.

**Pull request merged**
