### PR TITLE
Move justice transactions signature behind signer interface

### PR DESCRIPTION
**Pull request by ariard**
Build on top of #559.

### CODE REVIEW

**Comment by ariard** [comment]
Rebased on top of #598

**Comment by TheBlueMatt** [comment]
I'm really not a fan of the direction this is going in terms of OnchainTxHandler. More caching in OnchainTxHandler doesn't feel like the solution - its bad enough with the local_commitment and prev_local_commitment having almost entirely duplicated data but doing the same for remote commitment txn seems wrong. Its not *that* expensive to copy the data, and we shouldn't ever be in a state where we're tracking 10 different copies of remote HTLCs.

**Comment by ariard** [comment]
Closed by #610

**Comment by ariard** [comment]
Closed by #610

**Pull request closed without merging**
