### PR TITLE
Improve type safety for message failures

### PR DESCRIPTION
**Pull request by D4nte**
_Follow-up of #596_

Edit: Ready for review.

This a step towards a safer handling of failure code and associated data by using  a new `MessageFailure` enum instead of serialising the code and data on call site.

I see several ways to follow-up with this change:
1. Deserialise all possible message failures to `MessageFailure`, allowing the removal of the `HTLCFailReason::Reason` variant.
2. Continue to replace call site assignment of code value with instantiation of `MessageFailure` variables.

One downside of this solution is that I had to clone `ChannelUpdate`. Let me know if you'd prefer I optimise this before merging.

### CODE REVIEW

**Comment by jkczyz** [comment]
Concept ACK

Would love to see the code move in this direction, too. Thanks for jumping on this!

**Comment by TheBlueMatt** [comment]
Yep, what Jeff said!

**Comment by D4nte** [comment]
Need to sort build on old Rust toolchain 😟

**Comment by jkczyz** [comment]
> Need to sort build on old Rust toolchain 😟

Looks like you're running into issues on 1.22.0 with matching enum variants. The syntax is a bit more verbose in this version. You can reproduce the errors using:

```cargo +1.22.0 check -p lightning```
```cargo +1.22.0 test -p lightning```

You might find the [`wire`](https://github.com/rust-bitcoin/rust-lightning/blob/master/lightning/src/ln/wire.rs) module useful as an example of the syntax if the compiler messages aren't helpful.

**Comment by D4nte** [comment]
> > Need to sort build on old Rust toolchain 😟
> 
> Looks like you're running into issues on 1.22.0 with matching enum variants. The syntax is a bit more verbose in this version. You can reproduce the errors using:
> 
> `cargo +1.22.0 check -p lightning`
> `cargo +1.22.0 test -p lightning`
> 
> You might find the [`wire`](https://github.com/rust-bitcoin/rust-lightning/blob/master/lightning/src/ln/wire.rs) [](/rust-bitcoin/rust-lightning/blob/HEAD@{2020-04-21T17:04:49Z}/lightning/src/ln/wire.rs) module useful as an example of the syntax if the compiler messages aren't helpful.

Yep, thanks, no worries. I was working in Rust already when they did those improvements on the compiler where it is able to infer referencing. It's now ready for review/merge.

**Comment by jkczyz** [comment]
> _Follow-up of #596_
> 
> Edit: Ready for review.
> 
> This a step towards a safer handling of failure code and associated data by using a new `MessageFailure` enum instead of serialising the code and data on call site.
> 
> I see several ways to follow-up with this change:
> 
> 1. Deserialise all possible message failures to `MessageFailure`, allowing the removal of the `HTLCFailReason::Reason` variant.
> 2. Continue to replace call site assignment of code value with instantiation of `MessageFailure` variables.
> 

I have a bit of a preference to make all these changes in one PR rather than leaving the code in an intermediary state. Or at very least for (2). @TheBlueMatt What do you think?

> One downside of this solution is that I had to clone `ChannelUpdate`. Let me know if you'd prefer I optimise this before merging.

Looks like we were already cloning `ChannelUpdate` inside `peer_disconnected`. Or were you referring to somewhere else?

**Comment by TheBlueMatt** [comment]
Yea, at least personally I really don't mind a larger PR that removes `HTLCFailReason::Reason` and replaces it with types, obviously with smaller intermediary commits, though.

**Comment by D4nte** [comment]
> Looks like we were already cloning `ChannelUpdate` inside `peer_disconnected`. Or were you referring to somewhere else?

Ah yes indeed, all good.

**Comment by D4nte** [comment]
> Yea, at least personally I really don't mind a larger PR that removes `HTLCFailReason::Reason` and replaces it with types, obviously with smaller intermediary commits, though.

Ok cool, will do that then.

**Comment by TheBlueMatt** [comment]
@D4nte any plans on updating this?

**Comment by D4nte** [comment]
> @D4nte any plans on updating this?

Hi @TheBlueMatt, I don't see an opportunity to follow-up within the next two months. I'll close for now.

**Pull request closed without merging**
