### PR TITLE
Score channels on payment (WIP)

### PR DESCRIPTION
**Pull request by sourabhmarathe**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Looks like the current diff here includes a revert of #622?

**Comment by moneyball** [comment]
Cool! I just skimmed through the code, but I am curious if this scoring would be backed up in case the node restarts? I see in a comment the scoring data is stored in DirectionalChannelInfo ... is that data already included in a backup?

**Comment by sourabhmarathe** [comment]
> Looks like the current diff here includes a revert of #622?

Yes, it does. I think something went wrong with the timing of my the commits I had. I'm going to recreate this branch somewhere else and redo opening this draft PR in another location.

**Comment by sourabhmarathe** [comment]
> Cool! I just skimmed through the code, but I am curious if this scoring would be backed up in case the node restarts? I see in a comment the scoring data is stored in DirectionalChannelInfo ... is that data already included in a backup?

I think because DirectionalChannelInfo implements serialization, it would make sense to do so for ChannelScore as well. I did implement the Readable and Writeable traits for ChannelScore, but there might be more that is needed to make the struct serializable.

**Pull request closed without merging**
