### PR TITLE
[WIP] Add more comments in BOLT 5 specific tests to complete review

### PR DESCRIPTION
**Pull request by ariard**
Ongoing work to help review of BOLT 5, will obviously need #305 and #311 first.

Also extend some tests to cover more cases

### CODE REVIEW

**Comment by ariard** [comment]
Okay, I think we're mostly good after a first pass on BOLT 5

Some notes on requirements not added as test comments
1. MUST wait until the OP_CHECKSEQUENCEVERIFY delay has passed (as specified by the remote node's to_self_delay field) before spending the output => wallet job
2. MAY simply monitor the contents of the most-work chain for transactions => ChainWatchInterface job
3. MAY monitor (valid) broadcast transactions (a.k.a the mempool) =>  we close this way by requiring transactions matched with their height in ChannelMonitor, IMO would complexify delay tracking
4. MUST NOT broadcast a commitment transaction for which it has exposed the per_commitment_secret => will be implicitly tested once rogue tx detection is landed
5. otherwise if the remote node is NOT irrevocably committed to the HTLC, MUST NOT resolve the output by spending it => kinda fuzzy, if commitment transaction is broadcast and HTLC isn't into it you can't resolve it with a preimage tx, more BOLT 2 wording

**Comment by TheBlueMatt** [comment]
Looks like the tests fail after the tests update?

**Comment by ariard** [comment]
No worries, I was extending a test when I realized then in fact I needed fail back dust HTLC of local commitment so I let it as it was, need to get #305 first

**Comment by ariard** [comment]
Closing, not appropriate anymore

**Pull request closed without merging**
