### PR TITLE
f - Provide channel_monitor with first per_commitment_point of channel

### PR DESCRIPTION
**Pull request by ariard**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
This looks like a fix against 2d8afeccdb4f5aa6232e6d87c6096e980b836072, which was April of this year, so should just go in as a normal PR with a test? I don't think this is blocking the 0.0.6 demo?

**Comment by TheBlueMatt** [comment]
Also kinda related: #195. Apparently we just don't handle the first commitment txn well in channel monitoring.

**Comment by ariard** [comment]
Yeah, working on a normal PR for this one, and also #195 (even if it's loosely related)

**Comment by ariard** [comment]
See #230, will close it when I open PR for better way to provide per_commitment_point and keys interface tests.

**Comment by ariard** [comment]
New commits in #230 should do the job I think

**Pull request closed without merging**
