### PR TITLE
Fix non-HTLC-inclusion balance calculation (mark II)

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by savil** [comment]
How did you discover this? Would it be worth having test coverage here?

**Comment by TheBlueMatt** [comment]
If you send two payments at almost the same time you may see this (or maybe it's just back-to-back). Obviously it'd be nice to have test coverage but I'm not sure exactly how to do that aside from write out a ton of scenarios and then test them against each client.

**Comment by savil** [comment]
got it, yeah, I don't have any good ideas for testing it for now, but something to keep in the back of my mind

**Comment by TheBlueMatt** [comment]
Appears to work.

**Pull request merged**
