### PR TITLE
Fix encoding/decoding for OpenChannel

### PR DESCRIPTION
**Pull request by yuntai**
PR #119 fails on `no_existing_test_breakage()` which uses hex from this buggy
encoding. 

This PR fails at the same spot. Not sure I should edit hex or it's better to regenerate hex with this fix.

### CODE REVIEW

**Comment by yuntai** [comment]
ah, it's encrypted. can't really edit hex

**Comment by TheBlueMatt** [comment]
It looked right to me to begin with. I don't think you write a 0 if the scriptpubkey is missing - its determined by a feature bit, so its just missing.

**Comment by yuntai** [comment]
ah.. don't know what I was thinking. clearly (option_upfront_shutdown_script)
closing.

**Comment by yuntai** [comment]
actually bit confused. The spec says 
```
- if both nodes advertised the option_upfront_shutdown_script feature:
MUST include either a valid shutdown_scriptpubkey as required by shutdown scriptpubkey, or a zero-length shutdown_scriptpubkey.
- otherwise:
MAY include shutdown_scriptpubkey.
```
so regardless of the feature bit shutdown_scriptpubkey may still come. if zero length is not included, the message is not self-containing-parseable-complete (need to depend on EOF or frame length which the spec authors seem to try to avoid).

**Pull request closed without merging**
