### PR TITLE
block-sync: poll: make best known chain tip optional

### PR DESCRIPTION
**Pull request by valentinewallace**
For clients who are bootstrapping and have no best known tip. Unless I'm missing something here.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Hmm, how are you trying to use `Poll`, specifically? The `synchronize_listeners` method in block-sync/init takes a `BlockSource` instead, which doesn't require a previous tip.

**Comment by valentinewallace** [comment]
> Hmm, how are you trying to use `Poll`, specifically? The `synchronize_listeners` method in block-sync/init takes a `BlockSource` instead, which doesn't require a previous tip.

`SpvClient::new` requires a chain tip.

**Comment by TheBlueMatt** [comment]
> And if we're starting a fresh node and had no reason to call synchronize_listeners

Ah, good point. I wonder if we're better off just passing a `None` in to `SpvClient` instead, indicating a fresh node. What do you think @jkczyz ?

**Comment by jkczyz** [comment]
> > And if we're starting a fresh node and had no reason to call synchronize_listeners
> 
> Ah, good point. I wonder if we're better off just passing a `None` in to `SpvClient` instead, indicating a fresh node. What do you think @jkczyz ?

How about another utility in `init` that given a `Network` returns a `ValidatedBlockHeader` of the genesis block?

**Comment by TheBlueMatt** [comment]
> How about another utility in init that given a Network returns a ValidatedBlockHeader of the genesis block?

That would end up downloading the full chain, no? Ideally we'd just start from the current tip because we don't care about any of the historical data.

**Comment by jkczyz** [comment]
> That would end up downloading the full chain, no? Ideally we'd just start from the current tip because we don't care about any of the historical data.

True. Giving `None` to `SpvClient` would be preferable then I suppose.

**Comment by TheBlueMatt** [comment]
We could also do a util function in init that returns the current best block as a `ValidatedBlockHeader`, which would maybe be more explicit in the sense that you have to call something that has the word "fresh_node" in it or so.

**Comment by jkczyz** [comment]
> We could also do a util function in init that returns the current best block as a `ValidatedBlockHeader`, which would maybe be more explicit in the sense that you have to call something that has the word "fresh_node" in it or so.

Hmm... ok had some time to think about this. Doesn't calling `synchronize_listeners` without any listeners already do what we want?

We could make a utility that does this though technically it would ignore the `Network` parameter. Alternatively, we could refactor the first four lines of `synchronize_listeners` into a separate `pub` function -- essentially what you suggested -- and use it in `synchronize_listeners`. Maybe call it `validate_best_block_header` given calling it `fresh_node` wouldn't be applicable in this context.

**Comment by TheBlueMatt** [comment]
Either sounds good to me, seems like it would have a similar public API.

**Comment by jkczyz** [comment]
Superseded by #818.

**Pull request closed without merging**
