### PR TITLE
Add rpc sync method

### PR DESCRIPTION
**Pull request by valentinewallace**
Adds a synchronous `call_method` to the RPC client.

Not in the greatest shape atm.

### CODE REVIEW

**Comment by jkczyz** [comment]
Rather than modifying this code, would it be sufficient to have the user call `Runtime::block_on` with `RpcClient::call_method` in their own code? Then exposing the appropriate methods as `pub` would only be necessary.

I'm just little weary of creating a runtime within the library if it could be avoided. Not doing so would give users more flexibility, too.

**Comment by valentinewallace** [comment]
Hm, `call_method` is called quite frequently in the sample, so it'd certainly look a bit nicer if it were supported by RpcClient directly. Doesn't seem like the craziest thing for it to support a synchronous `call_method`. 

Why would that be more flexible, since it's behind a feature flag anyway? :)

**Comment by jkczyz** [comment]
> Hm, `call_method` is called quite frequently in the sample, so it'd certainly look a bit nicer if it were supported by RpcClient directly. Doesn't seem like the craziest thing for it to support a synchronous `call_method`.
> 

FWIW, a neat way to make things look cleaner instead of wrapping each call is to define a trait locally and implement the trait for whatever object that is defined elsewhere. Then you can still make it look like a simple method call.

> Why would that be more flexible, since it's behind a feature flag anyway? :)

It would allow users to customize the `Runtime` instead of always using the default, which they can do with a builder:

https://docs.rs/tokio/1.2.0/tokio/runtime/struct.Builder.html

**Comment by TheBlueMatt** [comment]
Yea, I'm not sure this approach makes sense - if someone is using tokio, they're probably better off just starting a runtime at program start and using that instead of spawning a new runtime to do initial sync and then another one later. Concretely, this PR also seems to make a bunch of things only available if you build with the new runtime feature, even though they also make sense without it (eg if the user has a non-multi-threaded tokio runtime?).

**Comment by valentinewallace** [comment]
Gotcha gotcha. Not the foremost expert on runtimes so I'm fine to defer to you guys :stuck_out_tongue:

**Pull request closed without merging**
