### PR TITLE
Panic on txn with value > 21mill in ChannelMonitor::block_connected, Clean up fuzz targets a bit

### PR DESCRIPTION
**Pull request by TheBlueMatt**
One cleanup to fuzz target infrastructure to make it easier to work with, one fix for a failing test.

### CODE REVIEW

**Comment by jkczyz** [comment]
> Previously, in each of our fuzz tests we had a dummy test which
> had a hard-coded hex string which it passed into the fuzz target
> so that when a failing test case was found, its hex could be
> copied into the test and you could run cargo test to analyze the
> failure. However, this was somewhat unwieldy as converting large
> tests back and forth between hex and raw files is quite annoying.
> 

Does someone running the test need to copy the hex into a file?

> Instead, we replace each of those tests with a test in each target
> that looks for files in fuzz/test_cases and runs each file it finds.

Or will a failing fuzz test case produce such a file which then just needs to be copied?

**Comment by TheBlueMatt** [comment]
Right, previously if you found a failing test, you had to hexdump it and copy the (often huge) hex into the fuzz file's test case. Now you can just cp the file.

**Comment by jkczyz** [comment]
> Right, previously if you found a failing test, you had to hexdump it and copy the (often huge) hex into the fuzz file's test case. Now you can just cp the file.

Could you add documentation for this? Or -- if documentation for fuzzing currently doesn't exist -- open an issue?

**Comment by TheBlueMatt** [comment]
Done. #475

**Pull request merged**
