### PR TITLE
add .editorconfig to ensure we use tabs, not spaces

### PR DESCRIPTION
**Pull request by savil**
relevant to #40 as well

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
It looks like not many editors actually support .editorconfig (eg no Vim/Emacs support). Do vim headers at the top of each file work better across editors (that has much better support, no?).

**Comment by savil** [comment]
Folks can install a plugin for vim, etc

**Comment by TheBlueMatt** [comment]
They could, but if they're gonna do that they can more easily tweak their config to just set the appropriate modes if the file is in a given folder. Adding configs is to help people who aren't active contributors or are new avoid hitting the mistake, and making them install a plugin defeats that purpose.

**Comment by savil** [comment]
that's fair.

I'm personally not a fan of adding the vim header (I think you mean http://vim.wikia.com/wiki/Modeline_magic?) to every source file. It adds unnecessary visual noise. I also couldn't find a reference on editor compatibility -- and what I could hinted at the answer being: not much.

Overall, to be beginner friendly, I'd much support switching to `rustfmt`, since that is the direction the rust community is heading towards.

**Comment by TheBlueMatt** [comment]
Hmm, that's a shame. Sadly rustfmt isn't smart enough to detect custom alignment which means you cant do anything manual (eg the manual alignment of some stuff like the endian conversion functions where the readability is clearly helped by manually aligning and you're more likely to see bugs visually there), so that's not really an option (yet, luckily using tabs makes manual alignment detection easy - if you're using spaces, that's probably why...) either.

**Comment by TheBlueMatt** [comment]
I guess best to just merge this as-is, then, at least some people may be helped :/.

**Pull request merged**
