### PR TITLE
Add subcrate which impls a simple SPV client from Bitcoin Core RPC

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This is still very much a WIP, and I want to reduce the dependencies to at least not rely on hyper as well as actually *implement* the REST-based client, though doing so should be trivial.

This adds a new subcrate `lightning-http-blocks` which is designed
to make it easier to get up-and-running by removing the effort of
building an SPV client and fetching the chain.

Instead of building a P2P client (and all the address management
that entails), this focuses on building a trivial SPV client which
can fetch from several instances of an abstract BlockSource. Then,
we provide two example BlockSource implementations that can fetch
from Bitcoin Core's RPC interface and Bitcoin Core's REST interface.

The code here is taken with heavy modifications from
rust-lightning-bitcoinrpc.

Addresses #627.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Still a bit raw in terms of code quality and still need testing, but its a thing, and worth at least a glance-over.

**Comment by TheBlueMatt** [comment]
@valentinewallace if you feel up to it feel free to take this over! Or @jkczyz if so inclined.

**Comment by jkczyz** [comment]
> @valentinewallace if you feel up to it feel free to take this over! Or @jkczyz if so inclined.

FYI, I've taken on this work and am currently working on some necessary refactoring to `BlockNotifier` and `ChainListener`.

Regarding eec4beb24b6f911b16f1edba5b55d9af4809db9d, the refactoring mentioned above may alter this in some way. I'm looking into that now and will ping you with any questions that I may have.

**Comment by jkczyz** [comment]
> FYI, I've taken on this work and am currently working on some necessary refactoring to `BlockNotifier` and `ChainListener`.

Here's the PR rebased on #649 using `BlockNotifier` instead of `AChainListener`: https://github.com/jkczyz/rust-lightning/commit/912014fb4a314fc92990ea015f735fd2df9fb1bd.

**Comment by TheBlueMatt** [comment]
Superseded by #763.

**Pull request closed without merging**
