### PR TITLE
Use workspaces to separate crates

### PR DESCRIPTION
**Pull request by rrybarczyk**
Use Rust's workspaces to separate the lightning and lightning-net-tokio crates. Tests from both workspaces will execute when `cargo test` is invoked at the top level directory.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Nice! Looks good, not sure why travis is failing on stable, but 1.22 looks like its because net-tokio doesn't support 1.22 (for various reasons). That's OK but we need to figure out how to make travis only run the main crate tests for 1.22.

**Comment by TheBlueMatt** [comment]
Hmm, looks like it needs a rebase, sadly. Are you still working on this @rrybarczyk ?

**Comment by rrybarczyk** [comment]
Yeah @TheBlueMatt, rebasing rn. Still need to figure out how to make Travis to skip over the net-tokio tests for Rust v1.22 though.

**Comment by TheBlueMatt** [comment]
Probably just update the script in .travis.yml to skip it based on the rustup show grep pattern already there.

**Comment by rrybarczyk** [comment]
So change [L18](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L18) from
`if [ "$(rustup show | grep default | grep stable)" != "" ]; then cd lightning-net-tokio && cargo build --verbose && cd ..; fi` 
to 
`if [ "$(rustup show | grep default | grep stable && rustup show | grep default | grep 1.22.0)" != "" ]; then cd lightning-net-tokio && cargo build --verbose && cd ..; fi`
?

**Comment by TheBlueMatt** [comment]
Ohhh, I guess I don't know how workspaces works? Can you change the root test to cd to the main workspace before testing so that it doesnt test all the workspaces, or does that test all the workspaces?

**Comment by rrybarczyk** [comment]
The command to just test the `lightning` workspace is `$ cargo -p lightning`, similarly to only test the `lightning-net-tokio` workspace is `$ cargo -p lightning-net-tokio`. 

I think I am having issues because I am not quite comfortable with Travis and am unclear on exactly what it should be building/testing for which version of Rust.

Can you let me know if my understanding of the `.travis.yml` file is correct:
[L14](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L14) - want to build the lightning crate for Rust stable, beta, 1.22.0, and 1.34.2
[L15](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L15) - remove old binaries
[L16](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L16) - want to test the `lightning` crate for Rust stable, beta, 1.22.0, and 1.34.2
[L17](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L17) - want to run the `lightning` crate fuzz tests for Rust 1.34.2
[L18](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L18) - want to build `lightning-net-tokio` for Rust stable
[L19](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L19) - want to run [L20](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L20) - [L32](https://github.com/rust-bitcoin/rust-lightning/blob/88fef649b15fa030cb91de76d58346a0bc408834/.travis.yml#L32) for Rust stable, these lines just perform logic required for Travis CI to work?

If my understanding of the above is correct, how do you feel about this update to the `script` section:
```
script:
     # Build workspaces with Rust stable, beta, and 1.34.0
     - if [ "$(rustup show | grep default | grep 1.22.0)" == "" ]; RUSTFLAGS="-C link-dead-code" cargo build --verbose
     - rm -f target/debug/lightning-* # Make sure we drop old test binaries
     # Build lightning workspace with Rust 1.22.0
     - if [ "$(rustup show | grep default | grep 1.22.0)" != "" ]; RUSTFLAGS="-C link-dead-code" cargo build --verbose -p lightning
     # Test workspaces for Rust stable, beta, and 1.34.2
     - if [ "$(rustup show | grep default | grep 1.22.0)" == "" ]; RUSTFLAGS="-C link-dead-code" cargo test --verbose
     # Test lightning workspace for 1.22.0
     - if [ "$(rustup show | grep default | grep 1.22.0)" != "" ]; RUSTFLAGS="-C link-dead-code" cargo test --verbose -p lightning
     # Run lightning workspace fuzz tests for Rust 1.34.2
     - if [ "$(rustup show | grep default | grep 1.34.2)" != "" ]; then cd lightning/fuzz && cargo test --verbose && ./travis-fuzz.sh; fi
     - if [ "$(rustup show | grep default | grep stable)" != "" ]; then
           wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
           tar xzf master.tar.gz &&
           cd kcov-master &&
           mkdir build &&
           cd build &&
           cmake .. &&
           make &&
           make install DESTDIR=../../kcov-build &&
           cd ../.. &&
           rm -rf kcov-master &&
           for file in target/debug/lightning-*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
           bash <(curl -s https://codecov.io/bash) &&
           echo "Uploaded code coverage"; fi
```

If my understanding is in correct, let me know where I am going wrong/what I am missing and I will update accordingly.

**Comment by TheBlueMatt** [comment]
Your understanding is correct, L20-33 do the codecov integration so we get code coverage reports....its some magic I just copied from their sample.

Your proposed version looks good, but you probably need to move the "Make sure we drop old test binaries" down to below the Build on Rust 1.22.0 line.

**Comment by TheBlueMatt** [comment]
Oops, sorry, merging #395 conflicted this PR. If you're working on it now can do a quick rebase + merge, otherwise may be a moving target...

**Comment by rrybarczyk** [comment]
@TheBlueMatt I am actively working on it rn. I had a syntax issue in the last .travis.yaml. I pushed a fix and it looks like everything is building ok rn, but it still has not finished all the way yet. Once this build (hopefully) passes, I can squash all my commits and have it ready to merge asap.

**Comment by rrybarczyk** [comment]
Ok, looks like all the builds are passing now! I squashed my WIP comments into one and pulled from master so everything should be up to date. Going to do a force push on this branch rn and it should be ready to merge

**Pull request merged**
